name: Integration tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v5
    
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.25
        
    - name: Build binary
      run: |
        go build -v -ldflags="-w -s" -o seqhasher seqhasher.go
        ls -l seqhasher
        
    - name: Run tests
      run: |
        cd test  
        chmod +x test2_binary.sh
        bash test2_binary.sh
