name: Test coverage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  coverage:
    name: Test coverage
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'

    - name: Install dependencies
      run: |
        go get -v -t -d ./...

    - name: Run tests with coverage
      run: go test -v -run TestAll -coverprofile=coverage.out -covermode=atomic
    
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        file: ./coverage.out
        flags: unittests
        token: ${{ secrets.CODECOV_TOKEN }}
