name: Go Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  test:
    name: Run Go Tests
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'

    - name: Install dependencies
      run: |
        go get -v -t -d ./...

    # - name: Run TestAll
    #  run: go test -v -run TestAll

    - name: Run TestParseFlags
      run: go test -v -run TestParseFlags

    - name: Run TestIsValidHashType
      run: go test -v -run TestIsValidHashType

    - name: Run TestGetInput
      run: go test -v -run TestGetInput

    - name: Run TestGetOutput
      run: go test -v -run TestGetOutput

    - name: Run TestProcessSequences
      run: go test -v -run TestProcessSequences

    - name: Run TestGetHashFunc
      run: go test -v -run TestGetHashFunc

    - name: Run TestCompressedInput
      run: go test -v -run TestCompressedInput

    - name: Run TestMainFunction
      run: go test -v -run TestMainFunction

    - name: Run TestGetInputError
      run: go test -v -run TestGetInputError

    - name: Run TestGetOutputError
      run: go test -v -run TestGetOutputError

    - name: Run TestPrintUsage
      run: go test -v -run TestPrintUsage

    - name: Upload test results
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: test-results
      if: failure()
